name: Deploy
on:
  release:
    types: [ created ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      CI: false

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16
      uses: actions/setup-node@v1
      with:
        node-version: 16
    - name: Install dependencies
      run: npm install
      
    - name: Build
      run: npm run build

    - name: Remove old build + copy new build to vps
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        source: "./build/*"
        target: "/root/front/build"
        strip_components: 1
        rm: true
  