name: Deploy
on:
  push:
    branches: [ master ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16
      uses: actions/setup-node@v1
      with:
        node-version: 16
    - name: Install dependencies
      run: npm install
    - name: Build
      run: npm run build
    - name: Remove old build in vps
      run: ssh ${{ secrets.HOST }}@${{ secrets.USERNAME }} -p ${{ secrets.PASSWORD }} 'rm -rf /var/www/html/*'
    - name: Copy to vps
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        source: "./build/*"
        target: "/var/www/html"
        strip_components: 1
  